[build]
	command = "# no build command"
	functions = "netlify/functions"
        publish = "netlify"
[functions]
        node_bundler = "esbuild"
[[plugins]]
    package = "netlify-plugin-chromium"
    [plugins.inputs]
      packageManager = "npm"
      setChromePathInEnv = false
      failBuildOnError = true
